# Use Ubuntu 14.04 as the base image (14.04 in ESM to 2026-04)
FROM ubuntu:14.04

ARG OLD_LIBRARY_PATH

ENV TZ="Europe/London"

# Set the working directory inside the container
WORKDIR /app

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    git-core \
    ruby \
    ruby-dev \
    rdoc \
    build-essential \
    curl \
    libmagickwand-dev \
    sqlite3 libsqlite3-dev \
    && apt-get clean

RUN apt install -y vim

# Needed for passenger-install-apache2-module
RUN apt-get install -y \
    libcurl4-openssl-dev \
    apache2 \
    libssl-dev \
    apache2-dev \
    libapr1-dev \
    libaprutil1-dev

# Copy the source code into the container
COPY . /app

###############################################################################
# Dependent applications and libraries
###############################################################################
# Install ImageMagick
RUN apt-get install libmagickwand-dev
# Install SQLite3
RUN apt-get install sqlite3 libsqlite3-dev
# Install LibYAML (https://pyyaml.org/wiki/LibYAML)
RUN apt-get install autoconf
RUN git clone https://github.com/yaml/libyaml && \
    cd libyaml && \
    ./bootstrap && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    rm -fr libyaml

# Other - mimemagic
RUN curl -O http://ftp.uk.debian.org/debian/pool/main/s/shared-mime-info/shared-mime-info_2.0-1_amd64.deb && \
    dpkg --install shared-mime-info_2.0-1_amd64.deb && \
    rm shared-mime-info_2.0-1_amd64.deb && \
    export FREEDESKTOP_MIME_TYPES_PATH=$(find / -name freedesktop.org.xml -print -quit)
# This requires mimemagic 0.2.1 at the latest, not available
# Possible candidate would be this commit v0.2.1:
#     https://github.com/mimemagicrb/mimemagic/commit/aa51152e9ba5a8d2b43c44a2dc4f28ce54498028

# Install Ruby dependencies from the Gemfile
RUN rm Gemfile.lock
RUN gem install bundler -v '1.17.0'
RUN bundle install
RUN gem install passenger

# Default command
#CMD ["ruby", "app.rb"]
